### ISSUE TITLE
Python executable/manage.py path issues starting carrot_daemon from outside a virtualenv/with supervisord

### ISSUE THREAD

**Issue by tehfink** [chris104957/django-carrot#100]
It seems the `carrot_daemon` management script [hard codes the python executable's name and assumes a location of `manage.py`](https://github.com/chris104957/django-carrot/blob/06030ed151c531426436ec6e10b2444a024dbfda/carrot/management/commands/carrot_daemon.py#L118), which means commands like this from a supervisord config will fail:
```bash
/usr/local/www/example.com/www./virtualenv/bin/python /usr/local/www/example.com/www./www_project/manage.py carrot_daemon start --logfile /usr/local/www/example.com/www./log/carrot.log
```
with an error like:
```python
Attempting to start the process
Traceback (most recent call last):
  File "/usr/local/www/example.com/www./www_project/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/www/example.com/www./virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/www/example.com/www./virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/www/example.com/www./virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/www/example.com/www./virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/www/example.com/www./virtualenv/lib/python3.6/site-packages/carrot/management/commands/carrot_daemon.py", line 152, in handle
    self.start(**options)
  File "/usr/local/www/example.com/www./virtualenv/lib/python3.6/site-packages/carrot/management/commands/carrot_daemon.py", line 128, in start
    proc = subprocess.Popen(options, stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python3': 'python3'
```

Changing line 118 of carrot_daemon.py to pass through, from the command line, the calling python executable and arg with the manage.py path seems to fix it, e.g.:
```python
options = [sys.executable, sys.argv[0], 'carrot', '--verbosity', str(options.get('verbosity', 2)),
```

**Comment by chris104957** [comment]
Sorry for the late reply. This change is unnecessary - here's how we configure carrot in our supervisor config file:

```
[program:django-carrot]
directory = /home/docker/code/app
command = python3 manage.py carrot --logfile carrot.log
```

It should just be a case of setting the directory to your `manage.py` file as shown above, and leaving the command as is
