### ISSUE TITLE
starting daemon fails with python 2

### ISSUE THREAD

**Issue by acourdavault** [chris104957/django-carrot#107]
Hello, 

I was setting up carrot with my existing django environment, which is in python2

problem this command fails because in python 2 DEVNULL is not in subprocess:
```
sudo python manage.py carrot_daemon start --logfile ./carrot.log                                                                                                     
Attempting to start the process                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                  
File "manage.py", line 22, in                                                                                                                                                                               
execute_from_command_line(sys.argv)                                                                                                                                                                             
File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in
execute_from_command_line                                                                                             utility.execute()                                                                                                                                                                                               
File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute                                                                                                               self.fetch_command(subcommand).run_from_argv(self.argv)                                                                                                                                                         
File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv                                                                                                             self.execute(*args, **cmd_options)                                                                                                                                                                              
File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute                                                                                                                   output = self.handle(*args, **options)                                                                                                                                                                          
File "/usr/local/lib/python2.7/dist-packages/carrot/management/commands/carrot_daemon.py", line 152, in handle                                                                                                       self.start(**options)                                                                                                                                                                                           
File "/usr/local/lib/python2.7/dist-packages/carrot/management/commands/carrot_daemon.py", line 128, in start                                                                                                        proc =
subprocess.Popen(options, stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)                                                                                                                         
AttributeError: 'module' object has no attribute 'DEVNULL'
```

**Do you see an alternative, or is it just not supposed to run on python 2?**

thank you

**Comment by chris104957** [comment]
this library is python3 only
