### ISSUE TITLE
When carrot experiences a database error it orphans tasks in "queued"/"published"

### ISSUE THREAD

**Issue by MikeSandford** [chris104957/django-carrot#83]
I'm using sqlite since I'm still heavy in development and my database is changing a lot.  I wrote a small script to totally annihilate the database.  When I run this and then try and submit new tasks (a very strange thing to do, admittedly) carrot will fail on the first job and not try any more jobs - presumably the right thing to do!

But it also orphans that first job in "published" on the "queued" page of carrot-monitor.  I don't think there's any way for me to get it out of there short of destroying the database again.  It's not a huge deal since I'm doing this quite a lot but it makes me wonder if there isn't some kind of subtle race condition here.

Here's a stacktrace of what went wrong:
```
default-consumer-1 2018-06-02 20:16:07,941 INFO:: default-consumer-1 2018-06-02 20:16:07,941 INFO:: Task items.jobs.ocr_page completed successfully with response None
Exception in thread default-consumer-1:
Traceback (most recent call last):
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: disk I/O error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/carrot/consumer.py", line 412, in run
    self.connection.ioloop.start()
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/pika/adapters/select_connection.py", line 209, in start
    self._poller.start()
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/pika/adapters/select_connection.py", line 495, in start
    self.poll()
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/pika/adapters/select_connection.py", line 935, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/pika/adapters/select_connection.py", line 625, in _dispatch_fd_events
    handler(fileno, events)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/pika/adapters/base_connection.py", line 395, in _handle_events
    self._handle_read()
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/pika/adapters/base_connection.py", line 449, in _handle_read
    self._on_data_available(data)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/pika/connection.py", line 1938, in _on_data_available
    self._process_frame(frame_value)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/pika/connection.py", line 2072, in _process_frame
    self._deliver_frame_to_channel(frame_value)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/pika/connection.py", line 1479, in _deliver_frame_to_channel
    self._channels[value.channel_number]._handle_content_frame(value)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/pika/channel.py", line 996, in _handle_content_frame
    self._on_deliver(*response)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/pika/channel.py", line 1125, in _on_deliver
    header_frame.properties, body)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/carrot/consumer.py", line 301, in on_message
    log = self.__get_message_log(properties, body)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/carrot/consumer.py", line 119, in __get_message_log
    log = self.get_message_log(properties, body)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/carrot/consumer.py", line 156, in get_message_log
    log = MessageLog.objects.get(uuid=properties.message_id)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/models/query.py", line 397, in get
    num = len(clone)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/models/query.py", line 254, in __len__
    self._fetch_all()
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1066, in execute_sql
    cursor.execute(sql, params)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/sandford/personal/website/env/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 303, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: disk I/O error

^CShutdown requested
Attempting to stop 0 running threads
Successfully closed scheduler
```

Me: doctor it hurts when I do this
Doctor: well stop doing that!

I'm fine if this is the outcome.  But I wanted to report it anyhow.

**Comment by chris104957** [comment]
This is something that I come across during development in SQLite, too. Ultimately, SQLite just can't deal with the number of threads Carrot generates when its busy. Even in our production environment, which uses Postgres, we've had to increase the maximum number of DB connections as we have a lot of queues with quite high concurrency.

The easiest way at present of deleting the orphaned tasks is via the shell
```python
from carrot.models import MessageLog
MessageLog.objects.filter(status__in=['PUBLISHED', 'IN_PROGRESS']).delete()
```

I'm wondering whether its worth adding a button to the monitor which does this for you, and also purges the queues in rabbit

**Comment by chris104957** [comment]
closing due to lack of activity

**Comment by tehfink** [comment]
> I'm wondering whether its worth adding a button to the monitor which does this for you, and also purges the queues in rabbit

+1 purge button in the monitor
